### ISSUE TITLE
Real-time data availability

### ISSUE THREAD

**Issue by hugolgst** [University-of-Reading-Space-Science/HUXt#11]
Hello there, 

I am looking to see if the output data from the real-time computations would be available to the public. 
As far as I know, we only have the generated image but I would like to plot it differently, citing the University of Reading of course. 

Thanks in advance

**Comment by LukeBarnard** [comment]
Hello,

Thanks for your interest! I presume you mean the data that forms the foreacst we publish at https://research.reading.ac.uk/met-spate/huxt-forecast/ ? If so, this isn't strictly an issue with HUXt, as although we use HUXt to generate those forecasts, it is technically a separate project to this repo (which just hosts HUXt). But yes, we are happy to publish those data and will update the webpage with a download link at somepoint this week. I'll update and close this issue when I have done that. 

Cheers,

**Comment by hugolgst** [comment]
Hi again,

Yes, it is exactly this forecast I am talking about. Thank you very much! 
Looking forward to receiving the data

**Comment by LukeBarnard** [comment]
Hi,

A link is now provided to a hdf5 file containing the latest forecast data, licensed under the CC-BY-4.0 license. At somepoint soon I'll add a metafile up better describing the hdf5 file, but I've run out of time this week, and the hdf5 headers are fairly self-explanatory. Feel free to email me at l.a.barnard@reading.ac.uk or DM me here if you need any further assistance with this. 

Cheers,
Luke

**Comment by eabase** [comment]
@LukeBarnard 
I'm a bit confused here. You say it provides a link to the "forecast data", but is that already analyzed data (already modeled) or is it the raw input to the model?

**Comment by LukeBarnard** [comment]
The HDF5 file we publish on the website includes the boundary condition data (both ambient solar wind and CME inputs) required to reproduce the HUXt simulations. It doesn't contain all of the information included in the WSA and ConeCME files that we downloaded from the SWEEP API, as not all of this is needed to drive the dashboard. The file does also include all of the model outputs seen in the dashboard. There is a function in `huxt_ensembles.py` that recreates the right data structures to plot the dashboard from this HDF5 file.
