### ISSUE TITLE
Is there any source where you can also get the lift-off times for the CMEs?

### ISSUE THREAD

**Issue by eabase** [University-of-Reading-Space-Science/HUXt#13]
Does the data include, or are you aware how we can get the time it took for the CME to _lift-off_?

I have been told that usually the longer time it takes the CME for liftoff the more intensive/massive the CME would be. This makes sense from a momentum/inertia perspective, so it would be cool to add that as an additional color or parameter in the model. (Unless it is already there.)

Do you have any further insight on this?

**Comment by LukeBarnard** [comment]
Hi,

A range of CME catalogues exist, which provide various kinds of information about the characteristics of a CMEs eruption from the corona. Some of these provide the acceleration profile of the CME, from which the lift-off time could be inferred. However, there are more direct ways to estimate the mass/momentum of the CME, based on photometric analysis of the CME in coronagraphs. 

HUXt, however, is a reduced physics model that models the solar wind as an incompressible inviscid fluid. As such, HUXt only considers and models the solar wind speed; density is not a parameter in HUXt. Consequently, there is no way to direclty incorporate CME mass into HUXt. 

I'm going to close this as this isn't an issue that be persued with HUXt.

**Comment by eabase** [comment]
> HUXt, however, is a reduced physics model that models the solar wind as an incompressible inviscid fluid.

Very interesting! It's funny it is doing so well, even though it makes little sense (to me) to make the fluid approximation, when I would have expected a rare-gas approximation would have been better.

**Comment by eabase** [comment]
> I'm not familiar with exactly what the rare-gas approximation is. 

Sorry, I used the wrong language. I meant "rarefied" gas, as in *ideal gas*.
