### ISSUE TITLE
I Got some errors in running codes，so how should i do ? for example,

### ISSUE THREAD

**Issue by freebob** [University-of-Reading-Space-Science/HUXt#9]
code/test_huxt.py: 617 warnings
  /public/home/jzbao/.conda/envs/huxt/lib/python3.9/site-packages/h5py/_hl/dataset.py:767: DeprecationWarning: Passing None into shape arguments as an alias for () is deprecated.
    arr = numpy.ndarray(selection.mshape, dtype=new_dtype)

code/test_huxt.py::test_streaklines
  /public/home/jzbao/.conda/envs/huxt/lib/python3.9/site-packages/astropy/units/quantity.py:1233: AstropyDeprecationWarning: The truth value of a Quantity is ambiguous. In the future this will raise a ValueError.
    warnings.warn('The truth value of a Quantity is ambiguous. '

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html

**Comment by freebob** [comment]
thank you very much

**Comment by LukeBarnard** [comment]
Hi @freebob. These are only warnings of behaviours that will be decprecated in future versions of numpy and astropy. Therefore, everything is working as expected. We will resolve these deprecation warnings in a future update to HUXt, but providing you use HUXt with the appropriate environment, then it will work as expected. Thanks for your query.
